name: Linux

on: [ push, pull_request ]

env:
  BUILD_TYPE: Release
  QT_VERSION: "6.8.1"
  QT_ARCH: "linux_gcc_64"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          cache: true
          version: ${{env.QT_VERSION}}
          arch: ${{env.QT_ARCH}}

      - name: Install Dependencies
        run: sudo apt install libxkbcommon-x11-dev libxcb-cursor-dev libfuse2t64 -y

      - name: Configure CMake
        run: cmake . -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_INSTALL_PREFIX=/usr

      - name: Build
        run: cmake --build . --config $BUILD_TYPE

      - name: Install
        run: make DESTDIR="${{runner.workspace}}/dist" install

      - name: Download linuxdeploy
        run: |
          curl -L "https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage" -o ${{runner.workspace}}/linuxdeploy-x86_64.AppImage
          curl -L "https://github.com/linuxdeploy/linuxdeploy-plugin-appimage/releases/download/continuous/linuxdeploy-plugin-appimage-x86_64.AppImage" -o ${{runner.workspace}}/linuxdeploy-plugin-appimage-x86_64.AppImage
          curl -L "https://github.com/linuxdeploy/linuxdeploy-plugin-qt/releases/download/continuous/linuxdeploy-plugin-qt-x86_64.AppImage" -o ${{runner.workspace}}/linuxdeploy-plugin-qt-x86_64.AppImage
          chmod +x ${{runner.workspace}}/linuxdeploy-*.AppImage

      - name: Package
        run: |
          export OUTPUT="tenkan-$(git rev-parse --short HEAD)-x86_64.AppImage"
          ${{runner.workspace}}/linuxdeploy-x86_64.AppImage --appdir ${{runner.workspace}}/dist --output appimage --plugin qt -d ${{runner.workspace}}/dist/usr/share/applications/tenkan.desktop

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tenkan-linux
          path: ${{runner.workspace}}/tenkan/tenkan-*.AppImage