name: WebAssembly

on: [ push, pull_request ]

env:
  BUILD_TYPE: MinSizeRel
  QT_VERSION: "6.8.1"
  QT_HOST_ARCH: "linux_gcc_64"
  QT_ARCH: "wasm_singlethread"
  # https://doc.qt.io/qt-6/wasm.html#installing-emscripten
  EM_VERSION: "3.1.56"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Qt (Linux)
        uses: jurplel/install-qt-action@v4
        with:
          cache: true
          version: ${{env.QT_VERSION}}
          arch: ${{env.QT_HOST_ARCH}}

      - name: Install Qt (WASM)
        # https://github.com/jurplel/install-qt-action/issues/258
        uses: timangus/install-qt-action@deployed
        with:
          cache: true
          host: 'all_os'
          target: 'wasm'
          version: ${{env.QT_VERSION}}
          arch: ${{env.QT_ARCH}}
          # https://github.com/miurahr/aqtinstall/pull/846
          aqtsource: 'git+https://github.com/miurahr/aqtinstall.git'

      - name: Setup emsdk
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: ${{env.EM_VERSION}}
          actions-cache-folder: 'emsdk-${{env.EM_VERSION}}'

      - name: Configure CMake
        env:
          QT_HOST_PATH: ${{runner.workspace}}/Qt/${{env.QT_VERSION}}/gcc_64
        run: |
          mkdir dist && cd dist
          chmod +x ${{runner.workspace}}/Qt/$QT_VERSION/$QT_ARCH/bin/qt-cmake
          ${{runner.workspace}}/Qt/$QT_VERSION/$QT_ARCH/bin/qt-cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE

      - name: Build
        working-directory: ${{runner.workspace}}/tenkan/dist
        run: cmake --build . --config $BUILD_TYPE

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tenkan-wasm
          path: ${{runner.workspace}}/tenkan/dist